server:
  port: 30181
  servlet:
    context-path: /auth

auth:
  origin: "http://localhost:30180"

spring:
  datasource:
    url: jdbc:mysql://localhost:30305/RPUserDB
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

client:
  id: client
  name: retail-pulse
  redirect-uri: http://localhost:30180
  post-logout-redirect-uri: http://localhost:30180

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2:
            server:
              authorization: DEBUG
        web: INFO
  file:
    name: logs/iam.log

management:
  endpoints:
    web:
      exposure:
        include: "health"
    health:
      probes:
        enabled: true
      show-details: "never"