server.port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_access
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

client:
  id: client
  name: retail-pulse
  redirect-uri: http://localhost:4200
  post-logout-redirect-uri: http://localhost:4200

logging:
  level:
    org:
      springframework:
        security: TRACE
        security.oauth2:
            server:
              authorization: TRACE
        web: DEBUG
  file:
    name: logs/iam.log