server:
  port: 8081
  urlPrefix: /auth

auth:
  origin: "http://localhost:4200"
  issuer: "http://localhost:8081/auth"

spring:
  datasource:
    url: jdbc:mysql://localhost:30305/RPUserDB
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

client:
  id: client
  name: retail-pulse
  redirect-uri: http://localhost:4200
  post-logout-redirect-uri: http://localhost:4200

logging:
  level:
    org:
      springframework:
        security: INFO
        security.oauth2:
            server:
              authorization: INFO
        web: INFO
  file:
    name: logs/iam.log

management:
  endpoints: 
    web:
      exposure:
        include: "health"
    health:
      probes:
        enabled: true
      show-details: "never"