apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-rp-iam-app
  namespace: ns-retailpulse
data:
  application.yaml: |
    server:
      port: 8081

    auth:
      origin: "http://localhost:30080"

    spring:
      datasource:
        url: jdbc:mysql://mysql-rp-user:3306/RPUserDB
        iamname: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver

      jpa:
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        
    client:
      id: client
      name: retail-pulse
      redirect-uri: http://localhost:30080
      post-logout-redirect-uri: http://localhost:30080

    logging:
      level:
        root: INFO
        org:
          springframework:
            security: TRACE
        com.retailpulse: DEBUG
      file:
        name: logs/rp-iam.log

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-rp-iam
  namespace: ns-retailpulse
  labels:
    app: deploy-rp-iam  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-rp-iam
  template:
    metadata:
      labels:
        app: deploy-rp-iam
    spec:
      containers:
      - image: docker.io/casperyap/rp-iam-app:v0.1.0
        name: myapp        
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        resources: {}
      volumes:
      - name: config-volume
        configMap:
          name: cm-rp-iam-app

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy-rp-iam
  name: svc-rp-iam
spec:
  selector:
    app: deploy-rp-iam
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30081  
  type: NodePort